# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mail_chimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mail_chimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: 15130fdbaf50721bd816912f3bdc1d66bdad5050447b489bd4312e4e16f1e21c8a68d9b431d4cbea28fc2adbb07988c687b5bd0f0b0ec8d3111ab905617919cd

test:
  secret_key_base: a0f93989eb336b5f9df0e4ed3cce40cf1af1fcec3ce67c091dd6e4ffe1d9a2180393ee1cae66401f49889f07d20f6dc43c8dcdf4ab270a56e87d976bb3c4c378

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mail_chimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mail_chimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>